version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - npm
  commit-message:
    prefix: deps
  groups:
    all-minor-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    all-major:
      patterns:
      - '*'
      update-types:
      - major
- package-ecosystem: npm
  directory: /functions
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  labels:
  - dependencies
  - functions
  commit-message:
    prefix: deps(functions)
  groups:
    all-minor-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    all-major:
      patterns:
      - '*'
      update-types:
      - major
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  labels:
  - dependencies
  - ci
  commit-message:
    prefix: ci
  groups:
    all-minor-patch:
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    all-major:
      patterns:
      - '*'
      update-types:
      - major
  open-pull-requests-limit: 5
