// dd-rum.ts — Datadog Real User Monitoring
// Auto-generated by Dobeu Automation Architect
//
// Install: npm install @datadog/browser-rum @datadog/browser-logs
// Import in your app entry point (main.tsx, index.tsx, App.tsx):
//   import './dd-rum'
//
// Required env vars:
//   VITE_DD_RUM_APPLICATION_ID=<create in Datadog UX Monitoring > RUM Applications>
//   VITE_DD_RUM_CLIENT_TOKEN=<from your RUM Application settings>
//   VITE_DD_ENV=production|staging
//   VITE_DD_SERVICE=your-service-name
//   VITE_DD_VERSION=1.0.0

import { datadogRum } from '@datadog/browser-rum';
import { datadogLogs } from '@datadog/browser-logs';

datadogRum.init({
  applicationId: import.meta.env.VITE_DD_RUM_APPLICATION_ID || '',
  clientToken: import.meta.env.VITE_DD_RUM_CLIENT_TOKEN || '',
  site: 'datadoghq.com',
  service: import.meta.env.VITE_DD_SERVICE || 'dobeu-frontend',
  env: import.meta.env.VITE_DD_ENV || 'production',
  version: import.meta.env.VITE_DD_VERSION || '1.0.0',
  sessionSampleRate: 100,
  sessionReplaySampleRate: 20,
  trackUserInteractions: true,
  trackResources: true,
  trackLongTasks: true,
  defaultPrivacyLevel: 'mask-user-input',
  allowedTracingUrls: [],
});

datadogLogs.init({
  clientToken: import.meta.env.VITE_DD_RUM_CLIENT_TOKEN || '',
  site: 'datadoghq.com',
  service: import.meta.env.VITE_DD_SERVICE || 'dobeu-frontend',
  env: import.meta.env.VITE_DD_ENV || 'production',
  forwardErrorsToLogs: true,
  sessionSampleRate: 100,
});

datadogRum.startSessionReplayRecording();

export { datadogRum, datadogLogs };
